from __future__ import annotations

import os
from pathlib import Path


AES_KEY_ENV_NAME = "PC_POWER_AES_KEY"
OUTPUT_FILE = "installer_build_secret.py"


def read_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    value = os.environ.get(AES_KEY_ENV_NAME) or read_env_file(root / ".env").get(AES_KEY_ENV_NAME)
    if not value:
        print(f"Build error: {AES_KEY_ENV_NAME} is missing. Set it in .env or environment variable.")
        return 2

    (root / OUTPUT_FILE).write_text(
        "# Auto-generated by build.bat. Do not commit.\n"
        f"EMBEDDED_AES_KEY = {value!r}\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
